spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
          format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.springframework.security: DEBUG
